### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by linasi** [RadicalLedger/did-siop-lib#23]
I would like to suggest to improve code quality a little.

File naming is not consistent through out the library. Some files are in camel case, others in snake case and others use hyphen to separate words. It would be a more clean approach to stick to one naming convention. I would personally go with hyphen.

In addition to that, it would be great to have some automatic code formatter like `prettier` integrated into the codebase. It would make it easier for others to contribute and avoid simple formatting inconsistencies like missed space, extra new line and so on.

**Comment by fidenz-chim** [comment]
All file names are now in kebab-case [f596608](https://github.com/RadicalLedger/did-siop-lib/commit/f59660867793e90880720c6cef4865d87f77b82f).  
npm [version 2.0.5](https://www.npmjs.com/package/did-siop/v/2.0.5)

**Comment by linasi** [comment]
Thank you @fidenz-chim ! Looks great.

Are you considering adding automatic code formatter like `prettier`?

**Comment by fidenz-chim** [comment]
prettier added. Now at every commit, prettier runs automatically for changes committing. Check [ReadMe](https://github.com/RadicalLedger/did-siop-lib/tree/master#code-formatting) for more info. [6657913]https://github.com/RadicalLedger/did-siop-lib/commit/66579139adc8da80bae7d38a29f76eb046ae52a9
