### ISSUE TITLE
Questions/requests

### ISSUE THREAD

**Issue by linasi** [RadicalLedger/did-siop-lib#25]
A few questions/requests that came up while playing with the library:

1. - Is there a way to overwrite/remove predefined resolvers? I might want to use only one and skip the default ones. Now it might take quite some time to resolve a DID when it goes through all the resolvers in the list.
2. - Example with VP Data would be nice to have in the docs
3. - What are these empty clauses for https://github.com/RadicalLedger/did-siop-lib/blob/master/src/core/RP.ts#L94 ? 
4. - `#addSigningParams` description in README.md is missing parameters
5. - Why request contains `did_authn` scope in `scope=openid%20did_authn` param? I can’t find it anywhere in https://openid.net/specs/openid-connect-self-issued-v2-1_0.html#name-scope

**Comment by fidenz-chim** [comment]
1. Fixed [b2be84b](https://github.com/RadicalLedger/did-siop-lib/commit/b2be84b00c72adb2fb12a343e3f1dec48f1656ba)
2. Updated [README](https://github.com/RadicalLedger/did-siop-lib/tree/master#code-samples)
3. Removed as not relevant
4. Now README matches implementation
5. Moving to a new Issue for better management

**Comment by linasi** [comment]
Thank you @fidenz-chim!

Everything looks good to me. Could you please tell me what has been updated regarding question number 1? I can't find any changes related to managing resolvers.

**Comment by fidenz-chim** [comment]
@linasi , Sorry the link I provided does not give enough info. Please check [this](https://github.com/RadicalLedger/did-siop-lib/tree/master#did-resolvers) out. You can find more info with [unit tests](https://github.com/RadicalLedger/did-siop-lib/blob/03f500a90601677386b7729193c165798ca12a8c/test/did-siop-e2e.spec.ts#L198) 007.02, 007.03 & 007.04
