### ISSUE TITLE
ethr-did-resolver hot fix clarification needed

### ISSUE THREAD

**Issue by linasi** [RadicalLedger/did-siop-lib#26]
At the end of the README.md there is a section:
```
Hot Fix
chaneg following line in node_modules/ethr-did-resolver/lib/index.js (ln1087)
```
Is it possible to give more context why and when this hot fix is needed?

**Comment by fidenz-chim** [comment]
This was needed when did-siop-lib being used in another application which uses older version of Typescript. Upgrade the Typescript version to 4.7.4, eliminated the build issue.
